name: SonarCloud analysis

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
    paths:
      - '.github/workflows/cd.yml'
  workflow_dispatch:


jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: CD
        run: echo " Deploying "
